### ISSUE TITLE
enrollment process not working 

### ISSUE THREAD

**Issue by Mostafa-ewida** [Hack-Maze/backend-spring#16]
![image](https://github.com/Hack-Maze/backend-spring/assets/71707534/b2cd8177-47da-49d3-83fd-0aa44a4aa446)

![image](https://github.com/Hack-Maze/backend-spring/assets/71707534/6834aa09-ebc1-4c3b-8ca2-9d89b36b0a31)

**Comment by ziad-amer-1** [comment]
DONE!
